apiVersion: v2
name: cluster-oauth
description: Configure OpenShift cluster OAuth authentication providers
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - openshift
  - oauth
  - authentication
  - htpasswd
  - ldap
home: https://github.com/redhat-consulting/openshift-charts
sources:
  - https://github.com/redhat-consulting/openshift-charts
maintainers:
  - name: Red Hat Consulting
    email: consulting@redhat.com