apiVersion: v2
name: node-timezone
description: Configure timezone for OpenShift nodes using MachineConfig
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - openshift
  - timezone
  - machineconfig
home: https://github.com/redhat-consulting/openshift-charts
sources:
  - https://github.com/redhat-consulting/openshift-charts
maintainers:
  - name: Red Hat Consulting
    email: consulting@redhat.com