{{- if and .Values.global.enabled .Values.nmstate.enabled }}
apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: {{ .Values.nmstate.name }}
  namespace: {{ index .Values "helper-operator" "operators" "nmstate" "namespace" "name" }}
  labels:
    {{- include "network-nmstate.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec: {}
{{- end }}