{{- if and .Values.oauth.enabled .Values.rbac.clusterAdmins.enabled }}
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{ .Values.rbac.clusterAdmins.groupName }}
  labels:
    {{- include "cluster-oauth.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
users: {{ .Values.rbac.clusterAdmins.users | default (list) | toJson }}
{{- end }}