{{- if and .Values.oauth.enabled .Values.htpasswd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.htpasswd.secretName }}
  namespace: openshift-config
  labels:
    {{- include "cluster-oauth.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  htpasswd: {{ include "cluster-oauth.htpasswdData" . }}
{{- end }}