apiVersion: v2
name: node-tuning
description: Configure OpenShift node tuning parameters (max pods, system reserved resources)
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - openshift
  - node-tuning
  - max-pods
  - system-reserved
  - kubelet
home: https://github.com/redhat-consulting/openshift-charts
sources:
  - https://github.com/redhat-consulting/openshift-charts
maintainers:
  - name: Red Hat Consulting
    email: consulting@redhat.com