apiVersion: v1
entries:
  helper-operator:
  - annotations:
      category: Operators
    apiVersion: v2
    appVersion: "1.0"
    created: "2025-11-20T18:32:28.505536442-05:00"
    description: Helper chart for installing OpenShift Operators
    digest: 9071ac207dbeddfd821a52e358863af2774515637adf0eeca5c0714595848c38
    home: https://github.com/redhat-consulting/openshift-day2-gitops
    keywords:
    - helper
    - subchart
    - operator
    - openshift
    - olm
    maintainers:
    - email: consulting@redhat.com
      name: Red Hat Consulting
    name: helper-operator
    sources:
    - https://github.com/redhat-consulting/openshift-day2-gitops
    type: application
    urls:
    - https://jeanlopezxyz.github.io/cluster-gitops/charts/helper-operator-1.0.1.tgz
    version: 1.0.1
generated: "2025-11-20T18:32:28.505176516-05:00"