---
galaxy_info:
  author: Red Hat Consulting
  description: Deploy Helm chart repository using httpd
  license: Apache-2.0
  min_ansible_version: '2.14'

  platforms:
    - name: EL
      versions:
        - '8'
        - '9'

  galaxy_tags:
    - helm
    - repository
    - httpd

dependencies: []

collections:
  - ansible.posix
