apiVersion: v2
name: etcd-backup
description: Create a CronJob that performs ETCD Backup and stores the backup to a PV for OpenShift clusters
type: application
version: 1.0.0
appVersion: "1.0"

keywords:
  - openshift
  - etcd
  - backup
  - cronjob
  - security
  - disaster-recovery

home: https://github.com/redhat-consulting/openshift-charts
sources:
  - https://github.com/redhat-consulting/openshift-charts
maintainers:
  - name: Red Hat Consulting
    email: consulting@redhat.com