{{- if and .Values.global.enabled .Values.rbac.monitoringReaders.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-readers
  labels:
    {{- include "cluster-monitoring.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules", "alertmanagers", "prometheuses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list", "watch"]

{{- if or (gt (len .Values.rbac.monitoringReaders.users) 0) (gt (len .Values.rbac.monitoringReaders.groups) 0) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-readers
  labels:
    {{- include "cluster-monitoring.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-readers
subjects:
{{- range .Values.rbac.monitoringReaders.users }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}
{{- end }}
{{- range .Values.rbac.monitoringReaders.groups }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ . }}
{{- end }}
{{- end }}
{{- end }}