{{- if and .Values.global.enabled .Values.telemetry.remoteWrite.enabled .Values.telemetry.remoteWrite.basicAuth.username .Values.telemetry.remoteWrite.basicAuth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-remote-write-auth
  namespace: openshift-monitoring
  labels:
    {{- include "cluster-monitoring.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  username: {{ .Values.telemetry.remoteWrite.basicAuth.username | b64enc }}
  password: {{ .Values.telemetry.remoteWrite.basicAuth.password | b64enc }}
{{- end }}