{{- range $key, $operator := .Values.operators }}
{{- if and $operator.enabled $operator.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "helper-operator.namespace" (dict "operator" $operator "key" $key "Release" $.Release) }}
  labels:
    {{- include "helper-operator.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}-namespace
  annotations:
    {{- if $operator.syncwave }}
    argocd.argoproj.io/sync-wave: {{ $operator.syncwave | quote }}
    {{- else }}
    argocd.argoproj.io/sync-wave: {{ $.Values.global.syncwave | quote }}
    {{- end }}
{{- end }}
{{- end }}